client:
  alteal:
    day:
      start_hour: 5
      sup_confort_zone: 21
      inf_confort_zone: 19
    night:
      start_hour: 23
      sup_confort_zone: 18
      inf_confort_zone: 17
    buffer_zone: 0.5
    iot_entity_list:
      - 5e3ad75c598c292e8d09ff40
      - 62b95a7829c8132ec7bc1f18
    sensors_ids_list:
      - 59c3b4b02e616c0008afdc8d
      - 59c3be80bee9f849f51461d4
