name: Pylint

on: [push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: set up virtualmenv
        run: make install
      - name: Install Requirements
        run: make install
      - name: Run flake8
        run: make lint
      - name: Reformat
        run: make format
